// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/responseprotectionrule"
	"github.com/looplj/axonhub/internal/objects"
)

// ResponseProtectionRule is the model entity for the ResponseProtectionRule schema.
type ResponseProtectionRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Rule name
	Name string `json:"name,omitempty"`
	// Rule description
	Description string `json:"description,omitempty"`
	// Regex pattern to match response content
	Pattern string `json:"pattern,omitempty"`
	// Status holds the value of the "status" field.
	Status responseprotectionrule.Status `json:"status,omitempty"`
	// Response protection rule settings
	Settings     *objects.ResponseProtectionSettings `json:"settings,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResponseProtectionRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case responseprotectionrule.FieldSettings:
			values[i] = new([]byte)
		case responseprotectionrule.FieldID, responseprotectionrule.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case responseprotectionrule.FieldName, responseprotectionrule.FieldDescription, responseprotectionrule.FieldPattern, responseprotectionrule.FieldStatus:
			values[i] = new(sql.NullString)
		case responseprotectionrule.FieldCreatedAt, responseprotectionrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResponseProtectionRule fields.
func (_m *ResponseProtectionRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case responseprotectionrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case responseprotectionrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case responseprotectionrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case responseprotectionrule.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case responseprotectionrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case responseprotectionrule.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case responseprotectionrule.FieldPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pattern", values[i])
			} else if value.Valid {
				_m.Pattern = value.String
			}
		case responseprotectionrule.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = responseprotectionrule.Status(value.String)
			}
		case responseprotectionrule.FieldSettings:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field settings", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Settings); err != nil {
					return fmt.Errorf("unmarshal field settings: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResponseProtectionRule.
// This includes values selected through modifiers, order, etc.
func (_m *ResponseProtectionRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ResponseProtectionRule.
// Note that you need to call ResponseProtectionRule.Unwrap() before calling this method if this ResponseProtectionRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ResponseProtectionRule) Update() *ResponseProtectionRuleUpdateOne {
	return NewResponseProtectionRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ResponseProtectionRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ResponseProtectionRule) Unwrap() *ResponseProtectionRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResponseProtectionRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ResponseProtectionRule) String() string {
	var builder strings.Builder
	builder.WriteString("ResponseProtectionRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("pattern=")
	builder.WriteString(_m.Pattern)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("settings=")
	builder.WriteString(fmt.Sprintf("%v", _m.Settings))
	builder.WriteByte(')')
	return builder.String()
}

// ResponseProtectionRules is a parsable slice of ResponseProtectionRule.
type ResponseProtectionRules []*ResponseProtectionRule
