// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/responseprotectionrule"
	"github.com/looplj/axonhub/internal/objects"
)

// ResponseProtectionRuleUpdate is the builder for updating ResponseProtectionRule entities.
type ResponseProtectionRuleUpdate struct {
	config
	hooks     []Hook
	mutation  *ResponseProtectionRuleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ResponseProtectionRuleUpdate builder.
func (_u *ResponseProtectionRuleUpdate) Where(ps ...predicate.ResponseProtectionRule) *ResponseProtectionRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResponseProtectionRuleUpdate) SetUpdatedAt(v time.Time) *ResponseProtectionRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResponseProtectionRuleUpdate) SetDeletedAt(v int) *ResponseProtectionRuleUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResponseProtectionRuleUpdate) SetNillableDeletedAt(v *int) *ResponseProtectionRuleUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ResponseProtectionRuleUpdate) AddDeletedAt(v int) *ResponseProtectionRuleUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ResponseProtectionRuleUpdate) SetName(v string) *ResponseProtectionRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResponseProtectionRuleUpdate) SetNillableName(v *string) *ResponseProtectionRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ResponseProtectionRuleUpdate) SetDescription(v string) *ResponseProtectionRuleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ResponseProtectionRuleUpdate) SetNillableDescription(v *string) *ResponseProtectionRuleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPattern sets the "pattern" field.
func (_u *ResponseProtectionRuleUpdate) SetPattern(v string) *ResponseProtectionRuleUpdate {
	_u.mutation.SetPattern(v)
	return _u
}

// SetNillablePattern sets the "pattern" field if the given value is not nil.
func (_u *ResponseProtectionRuleUpdate) SetNillablePattern(v *string) *ResponseProtectionRuleUpdate {
	if v != nil {
		_u.SetPattern(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResponseProtectionRuleUpdate) SetStatus(v responseprotectionrule.Status) *ResponseProtectionRuleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResponseProtectionRuleUpdate) SetNillableStatus(v *responseprotectionrule.Status) *ResponseProtectionRuleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSettings sets the "settings" field.
func (_u *ResponseProtectionRuleUpdate) SetSettings(v *objects.ResponseProtectionSettings) *ResponseProtectionRuleUpdate {
	_u.mutation.SetSettings(v)
	return _u
}

// Mutation returns the ResponseProtectionRuleMutation object of the builder.
func (_u *ResponseProtectionRuleUpdate) Mutation() *ResponseProtectionRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResponseProtectionRuleUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResponseProtectionRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResponseProtectionRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResponseProtectionRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResponseProtectionRuleUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if responseprotectionrule.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized responseprotectionrule.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := responseprotectionrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResponseProtectionRuleUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := responseprotectionrule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResponseProtectionRule.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ResponseProtectionRuleUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ResponseProtectionRuleUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ResponseProtectionRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(responseprotectionrule.Table, responseprotectionrule.Columns, sqlgraph.NewFieldSpec(responseprotectionrule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(responseprotectionrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(responseprotectionrule.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(responseprotectionrule.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(responseprotectionrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(responseprotectionrule.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pattern(); ok {
		_spec.SetField(responseprotectionrule.FieldPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(responseprotectionrule.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(responseprotectionrule.FieldSettings, field.TypeJSON, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{responseprotectionrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResponseProtectionRuleUpdateOne is the builder for updating a single ResponseProtectionRule entity.
type ResponseProtectionRuleUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ResponseProtectionRuleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResponseProtectionRuleUpdateOne) SetUpdatedAt(v time.Time) *ResponseProtectionRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResponseProtectionRuleUpdateOne) SetDeletedAt(v int) *ResponseProtectionRuleUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResponseProtectionRuleUpdateOne) SetNillableDeletedAt(v *int) *ResponseProtectionRuleUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ResponseProtectionRuleUpdateOne) AddDeletedAt(v int) *ResponseProtectionRuleUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ResponseProtectionRuleUpdateOne) SetName(v string) *ResponseProtectionRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResponseProtectionRuleUpdateOne) SetNillableName(v *string) *ResponseProtectionRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ResponseProtectionRuleUpdateOne) SetDescription(v string) *ResponseProtectionRuleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ResponseProtectionRuleUpdateOne) SetNillableDescription(v *string) *ResponseProtectionRuleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPattern sets the "pattern" field.
func (_u *ResponseProtectionRuleUpdateOne) SetPattern(v string) *ResponseProtectionRuleUpdateOne {
	_u.mutation.SetPattern(v)
	return _u
}

// SetNillablePattern sets the "pattern" field if the given value is not nil.
func (_u *ResponseProtectionRuleUpdateOne) SetNillablePattern(v *string) *ResponseProtectionRuleUpdateOne {
	if v != nil {
		_u.SetPattern(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResponseProtectionRuleUpdateOne) SetStatus(v responseprotectionrule.Status) *ResponseProtectionRuleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResponseProtectionRuleUpdateOne) SetNillableStatus(v *responseprotectionrule.Status) *ResponseProtectionRuleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSettings sets the "settings" field.
func (_u *ResponseProtectionRuleUpdateOne) SetSettings(v *objects.ResponseProtectionSettings) *ResponseProtectionRuleUpdateOne {
	_u.mutation.SetSettings(v)
	return _u
}

// Mutation returns the ResponseProtectionRuleMutation object of the builder.
func (_u *ResponseProtectionRuleUpdateOne) Mutation() *ResponseProtectionRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResponseProtectionRuleUpdate builder.
func (_u *ResponseProtectionRuleUpdateOne) Where(ps ...predicate.ResponseProtectionRule) *ResponseProtectionRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResponseProtectionRuleUpdateOne) Select(field string, fields ...string) *ResponseProtectionRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResponseProtectionRule entity.
func (_u *ResponseProtectionRuleUpdateOne) Save(ctx context.Context) (*ResponseProtectionRule, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResponseProtectionRuleUpdateOne) SaveX(ctx context.Context) *ResponseProtectionRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResponseProtectionRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResponseProtectionRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResponseProtectionRuleUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if responseprotectionrule.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized responseprotectionrule.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := responseprotectionrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResponseProtectionRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := responseprotectionrule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResponseProtectionRule.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ResponseProtectionRuleUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ResponseProtectionRuleUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ResponseProtectionRuleUpdateOne) sqlSave(ctx context.Context) (_node *ResponseProtectionRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(responseprotectionrule.Table, responseprotectionrule.Columns, sqlgraph.NewFieldSpec(responseprotectionrule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResponseProtectionRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, responseprotectionrule.FieldID)
		for _, f := range fields {
			if !responseprotectionrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != responseprotectionrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(responseprotectionrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(responseprotectionrule.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(responseprotectionrule.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(responseprotectionrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(responseprotectionrule.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pattern(); ok {
		_spec.SetField(responseprotectionrule.FieldPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(responseprotectionrule.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(responseprotectionrule.FieldSettings, field.TypeJSON, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ResponseProtectionRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{responseprotectionrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
