// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/responseprotectionrule"
	"github.com/looplj/axonhub/internal/objects"
)

// ResponseProtectionRuleCreate is the builder for creating a ResponseProtectionRule entity.
type ResponseProtectionRuleCreate struct {
	config
	mutation *ResponseProtectionRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResponseProtectionRuleCreate) SetCreatedAt(v time.Time) *ResponseProtectionRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResponseProtectionRuleCreate) SetNillableCreatedAt(v *time.Time) *ResponseProtectionRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResponseProtectionRuleCreate) SetUpdatedAt(v time.Time) *ResponseProtectionRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResponseProtectionRuleCreate) SetNillableUpdatedAt(v *time.Time) *ResponseProtectionRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ResponseProtectionRuleCreate) SetDeletedAt(v int) *ResponseProtectionRuleCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ResponseProtectionRuleCreate) SetNillableDeletedAt(v *int) *ResponseProtectionRuleCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ResponseProtectionRuleCreate) SetName(v string) *ResponseProtectionRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ResponseProtectionRuleCreate) SetDescription(v string) *ResponseProtectionRuleCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ResponseProtectionRuleCreate) SetNillableDescription(v *string) *ResponseProtectionRuleCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPattern sets the "pattern" field.
func (_c *ResponseProtectionRuleCreate) SetPattern(v string) *ResponseProtectionRuleCreate {
	_c.mutation.SetPattern(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ResponseProtectionRuleCreate) SetStatus(v responseprotectionrule.Status) *ResponseProtectionRuleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ResponseProtectionRuleCreate) SetNillableStatus(v *responseprotectionrule.Status) *ResponseProtectionRuleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSettings sets the "settings" field.
func (_c *ResponseProtectionRuleCreate) SetSettings(v *objects.ResponseProtectionSettings) *ResponseProtectionRuleCreate {
	_c.mutation.SetSettings(v)
	return _c
}

// Mutation returns the ResponseProtectionRuleMutation object of the builder.
func (_c *ResponseProtectionRuleCreate) Mutation() *ResponseProtectionRuleMutation {
	return _c.mutation
}

// Save creates the ResponseProtectionRule in the database.
func (_c *ResponseProtectionRuleCreate) Save(ctx context.Context) (*ResponseProtectionRule, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResponseProtectionRuleCreate) SaveX(ctx context.Context) *ResponseProtectionRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResponseProtectionRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResponseProtectionRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResponseProtectionRuleCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if responseprotectionrule.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized responseprotectionrule.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := responseprotectionrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if responseprotectionrule.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized responseprotectionrule.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := responseprotectionrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := responseprotectionrule.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := responseprotectionrule.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := responseprotectionrule.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResponseProtectionRuleCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "ResponseProtectionRule.deleted_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ResponseProtectionRule.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ResponseProtectionRule.description"`)}
	}
	if _, ok := _c.mutation.Pattern(); !ok {
		return &ValidationError{Name: "pattern", err: errors.New(`ent: missing required field "ResponseProtectionRule.pattern"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ResponseProtectionRule.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := responseprotectionrule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResponseProtectionRule.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Settings(); !ok {
		return &ValidationError{Name: "settings", err: errors.New(`ent: missing required field "ResponseProtectionRule.settings"`)}
	}
	return nil
}

func (_c *ResponseProtectionRuleCreate) sqlSave(ctx context.Context) (*ResponseProtectionRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResponseProtectionRuleCreate) createSpec() (*ResponseProtectionRule, *sqlgraph.CreateSpec) {
	var (
		_node = &ResponseProtectionRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(responseprotectionrule.Table, sqlgraph.NewFieldSpec(responseprotectionrule.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(responseprotectionrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(responseprotectionrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(responseprotectionrule.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(responseprotectionrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(responseprotectionrule.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Pattern(); ok {
		_spec.SetField(responseprotectionrule.FieldPattern, field.TypeString, value)
		_node.Pattern = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(responseprotectionrule.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Settings(); ok {
		_spec.SetField(responseprotectionrule.FieldSettings, field.TypeJSON, value)
		_node.Settings = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResponseProtectionRule.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResponseProtectionRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResponseProtectionRuleCreate) OnConflict(opts ...sql.ConflictOption) *ResponseProtectionRuleUpsertOne {
	_c.conflict = opts
	return &ResponseProtectionRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResponseProtectionRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResponseProtectionRuleCreate) OnConflictColumns(columns ...string) *ResponseProtectionRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResponseProtectionRuleUpsertOne{
		create: _c,
	}
}

type (
	// ResponseProtectionRuleUpsertOne is the builder for "upsert"-ing
	//  one ResponseProtectionRule node.
	ResponseProtectionRuleUpsertOne struct {
		create *ResponseProtectionRuleCreate
	}

	// ResponseProtectionRuleUpsert is the "OnConflict" setter.
	ResponseProtectionRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ResponseProtectionRuleUpsert) SetUpdatedAt(v time.Time) *ResponseProtectionRuleUpsert {
	u.Set(responseprotectionrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsert) UpdateUpdatedAt() *ResponseProtectionRuleUpsert {
	u.SetExcluded(responseprotectionrule.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ResponseProtectionRuleUpsert) SetDeletedAt(v int) *ResponseProtectionRuleUpsert {
	u.Set(responseprotectionrule.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsert) UpdateDeletedAt() *ResponseProtectionRuleUpsert {
	u.SetExcluded(responseprotectionrule.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ResponseProtectionRuleUpsert) AddDeletedAt(v int) *ResponseProtectionRuleUpsert {
	u.Add(responseprotectionrule.FieldDeletedAt, v)
	return u
}

// SetName sets the "name" field.
func (u *ResponseProtectionRuleUpsert) SetName(v string) *ResponseProtectionRuleUpsert {
	u.Set(responseprotectionrule.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsert) UpdateName() *ResponseProtectionRuleUpsert {
	u.SetExcluded(responseprotectionrule.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *ResponseProtectionRuleUpsert) SetDescription(v string) *ResponseProtectionRuleUpsert {
	u.Set(responseprotectionrule.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsert) UpdateDescription() *ResponseProtectionRuleUpsert {
	u.SetExcluded(responseprotectionrule.FieldDescription)
	return u
}

// SetPattern sets the "pattern" field.
func (u *ResponseProtectionRuleUpsert) SetPattern(v string) *ResponseProtectionRuleUpsert {
	u.Set(responseprotectionrule.FieldPattern, v)
	return u
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsert) UpdatePattern() *ResponseProtectionRuleUpsert {
	u.SetExcluded(responseprotectionrule.FieldPattern)
	return u
}

// SetStatus sets the "status" field.
func (u *ResponseProtectionRuleUpsert) SetStatus(v responseprotectionrule.Status) *ResponseProtectionRuleUpsert {
	u.Set(responseprotectionrule.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsert) UpdateStatus() *ResponseProtectionRuleUpsert {
	u.SetExcluded(responseprotectionrule.FieldStatus)
	return u
}

// SetSettings sets the "settings" field.
func (u *ResponseProtectionRuleUpsert) SetSettings(v *objects.ResponseProtectionSettings) *ResponseProtectionRuleUpsert {
	u.Set(responseprotectionrule.FieldSettings, v)
	return u
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsert) UpdateSettings() *ResponseProtectionRuleUpsert {
	u.SetExcluded(responseprotectionrule.FieldSettings)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ResponseProtectionRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResponseProtectionRuleUpsertOne) UpdateNewValues() *ResponseProtectionRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(responseprotectionrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResponseProtectionRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResponseProtectionRuleUpsertOne) Ignore() *ResponseProtectionRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResponseProtectionRuleUpsertOne) DoNothing() *ResponseProtectionRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResponseProtectionRuleCreate.OnConflict
// documentation for more info.
func (u *ResponseProtectionRuleUpsertOne) Update(set func(*ResponseProtectionRuleUpsert)) *ResponseProtectionRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResponseProtectionRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResponseProtectionRuleUpsertOne) SetUpdatedAt(v time.Time) *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertOne) UpdateUpdatedAt() *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ResponseProtectionRuleUpsertOne) SetDeletedAt(v int) *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ResponseProtectionRuleUpsertOne) AddDeletedAt(v int) *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertOne) UpdateDeletedAt() *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ResponseProtectionRuleUpsertOne) SetName(v string) *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertOne) UpdateName() *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ResponseProtectionRuleUpsertOne) SetDescription(v string) *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertOne) UpdateDescription() *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdateDescription()
	})
}

// SetPattern sets the "pattern" field.
func (u *ResponseProtectionRuleUpsertOne) SetPattern(v string) *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetPattern(v)
	})
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertOne) UpdatePattern() *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdatePattern()
	})
}

// SetStatus sets the "status" field.
func (u *ResponseProtectionRuleUpsertOne) SetStatus(v responseprotectionrule.Status) *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertOne) UpdateStatus() *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdateStatus()
	})
}

// SetSettings sets the "settings" field.
func (u *ResponseProtectionRuleUpsertOne) SetSettings(v *objects.ResponseProtectionSettings) *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertOne) UpdateSettings() *ResponseProtectionRuleUpsertOne {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdateSettings()
	})
}

// Exec executes the query.
func (u *ResponseProtectionRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResponseProtectionRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResponseProtectionRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResponseProtectionRuleUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResponseProtectionRuleUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResponseProtectionRuleCreateBulk is the builder for creating many ResponseProtectionRule entities in bulk.
type ResponseProtectionRuleCreateBulk struct {
	config
	err      error
	builders []*ResponseProtectionRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the ResponseProtectionRule entities in the database.
func (_c *ResponseProtectionRuleCreateBulk) Save(ctx context.Context) ([]*ResponseProtectionRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResponseProtectionRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResponseProtectionRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResponseProtectionRuleCreateBulk) SaveX(ctx context.Context) []*ResponseProtectionRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResponseProtectionRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResponseProtectionRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResponseProtectionRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResponseProtectionRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResponseProtectionRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResponseProtectionRuleUpsertBulk {
	_c.conflict = opts
	return &ResponseProtectionRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResponseProtectionRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResponseProtectionRuleCreateBulk) OnConflictColumns(columns ...string) *ResponseProtectionRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResponseProtectionRuleUpsertBulk{
		create: _c,
	}
}

// ResponseProtectionRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of ResponseProtectionRule nodes.
type ResponseProtectionRuleUpsertBulk struct {
	create *ResponseProtectionRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResponseProtectionRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResponseProtectionRuleUpsertBulk) UpdateNewValues() *ResponseProtectionRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(responseprotectionrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResponseProtectionRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResponseProtectionRuleUpsertBulk) Ignore() *ResponseProtectionRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResponseProtectionRuleUpsertBulk) DoNothing() *ResponseProtectionRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResponseProtectionRuleCreateBulk.OnConflict
// documentation for more info.
func (u *ResponseProtectionRuleUpsertBulk) Update(set func(*ResponseProtectionRuleUpsert)) *ResponseProtectionRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResponseProtectionRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResponseProtectionRuleUpsertBulk) SetUpdatedAt(v time.Time) *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertBulk) UpdateUpdatedAt() *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ResponseProtectionRuleUpsertBulk) SetDeletedAt(v int) *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ResponseProtectionRuleUpsertBulk) AddDeletedAt(v int) *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertBulk) UpdateDeletedAt() *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ResponseProtectionRuleUpsertBulk) SetName(v string) *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertBulk) UpdateName() *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ResponseProtectionRuleUpsertBulk) SetDescription(v string) *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertBulk) UpdateDescription() *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdateDescription()
	})
}

// SetPattern sets the "pattern" field.
func (u *ResponseProtectionRuleUpsertBulk) SetPattern(v string) *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetPattern(v)
	})
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertBulk) UpdatePattern() *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdatePattern()
	})
}

// SetStatus sets the "status" field.
func (u *ResponseProtectionRuleUpsertBulk) SetStatus(v responseprotectionrule.Status) *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertBulk) UpdateStatus() *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdateStatus()
	})
}

// SetSettings sets the "settings" field.
func (u *ResponseProtectionRuleUpsertBulk) SetSettings(v *objects.ResponseProtectionSettings) *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *ResponseProtectionRuleUpsertBulk) UpdateSettings() *ResponseProtectionRuleUpsertBulk {
	return u.Update(func(s *ResponseProtectionRuleUpsert) {
		s.UpdateSettings()
	})
}

// Exec executes the query.
func (u *ResponseProtectionRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResponseProtectionRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResponseProtectionRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResponseProtectionRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
