package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/responseprotectionrule"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/server/biz"
)

// CreateResponseProtectionRule is the resolver for the createResponseProtectionRule field.
func (r *mutationResolver) CreateResponseProtectionRule(ctx context.Context, input ent.CreateResponseProtectionRuleInput) (*ent.ResponseProtectionRule, error) {
	return r.responseProtectionRuleService.CreateRule(ctx, input)
}

// UpdateResponseProtectionRule is the resolver for the updateResponseProtectionRule field.
func (r *mutationResolver) UpdateResponseProtectionRule(ctx context.Context, id objects.GUID, input ent.UpdateResponseProtectionRuleInput) (*ent.ResponseProtectionRule, error) {
	return r.responseProtectionRuleService.UpdateRule(ctx, id.ID, &input)
}

// DeleteResponseProtectionRule is the resolver for the deleteResponseProtectionRule field.
func (r *mutationResolver) DeleteResponseProtectionRule(ctx context.Context, id objects.GUID) (bool, error) {
	if err := r.responseProtectionRuleService.DeleteRule(ctx, id.ID); err != nil {
		return false, err
	}

	return true, nil
}

// UpdateResponseProtectionRuleStatus is the resolver for the updateResponseProtectionRuleStatus field.
func (r *mutationResolver) UpdateResponseProtectionRuleStatus(ctx context.Context, id objects.GUID, status responseprotectionrule.Status) (bool, error) {
	if _, err := r.responseProtectionRuleService.UpdateRuleStatus(ctx, id.ID, status); err != nil {
		return false, err
	}

	return true, nil
}

// BulkDeleteResponseProtectionRules is the resolver for the bulkDeleteResponseProtectionRules field.
func (r *mutationResolver) BulkDeleteResponseProtectionRules(ctx context.Context, ids []*objects.GUID) (bool, error) {
	if err := r.responseProtectionRuleService.BulkDeleteRules(ctx, objects.IntGuids(ids)); err != nil {
		return false, err
	}

	return true, nil
}

// BulkEnableResponseProtectionRules is the resolver for the bulkEnableResponseProtectionRules field.
func (r *mutationResolver) BulkEnableResponseProtectionRules(ctx context.Context, ids []*objects.GUID) (bool, error) {
	if err := r.responseProtectionRuleService.BulkEnableRules(ctx, objects.IntGuids(ids)); err != nil {
		return false, err
	}

	return true, nil
}

// BulkDisableResponseProtectionRules is the resolver for the bulkDisableResponseProtectionRules field.
func (r *mutationResolver) BulkDisableResponseProtectionRules(ctx context.Context, ids []*objects.GUID) (bool, error) {
	if err := r.responseProtectionRuleService.BulkDisableRules(ctx, objects.IntGuids(ids)); err != nil {
		return false, err
	}

	return true, nil
}

// PreviewResponseProtectionRule is the resolver for the previewResponseProtectionRule field.
func (r *mutationResolver) PreviewResponseProtectionRule(ctx context.Context, input ResponseProtectionRulePreviewInput) (*ResponseProtectionRulePreviewResult, error) {
	result, err := r.responseProtectionRuleService.Preview(ctx, biz.ResponseProtectionPreviewInput{
		Pattern:  input.Pattern,
		TestText: input.TestText,
		Settings: &objects.ResponseProtectionSettings{
			Action:      input.Settings.Action,
			Replacement: input.Settings.Replacement,
			Scopes:      input.Settings.Scopes,
		},
	})
	if err != nil {
		return nil, err
	}

	return &ResponseProtectionRulePreviewResult{
		Result:   result.Result,
		HasMatch: result.HasMatch,
	}, nil
}
